AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
